apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafkaclusterName}}
spec:
  kafka:
    version: 3.2.0
    replicas: {{ .Values.cluster.kafka.replicas}}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: nodeport
        port: 9094
        type: nodeport
        tls: true
        configuration:
          bootstrap:
            nodePort: 31140

    config:
      offsets.topic.replication.factor: {{ .Values.cluster.kafka.config.topicReplica}}
      transaction.state.log.replication.factor: {{ .Values.cluster.kafka.config.topicReplica}}
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.cluster.kafka.storage.size}}
        deleteClaim: false
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsGroup: 0
          runAsUser: 0
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: kafka
                topologyKey: kubernetes.io/hostname
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsGroup: 0
          runAsUser: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}